/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTachesRouteImport } from './routes/app.taches'
import { Route as AppRisquesRouteImport } from './routes/app.risques'
import { Route as AppRessourcesRouteImport } from './routes/app.ressources'
import { Route as AppProjetsRouteImport } from './routes/app.projets'
import { Route as AppProfilEditRouteImport } from './routes/app.profil-edit'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppPartenairesRouteImport } from './routes/app.partenaires'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppClientRouteImport } from './routes/app.client'
import { Route as AppTachesAddRouteImport } from './routes/app.taches/add'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTachesRoute = AppTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AppRoute,
} as any)
const AppRisquesRoute = AppRisquesRouteImport.update({
  id: '/risques',
  path: '/risques',
  getParentRoute: () => AppRoute,
} as any)
const AppRessourcesRoute = AppRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsRoute = AppProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilEditRoute = AppProfilEditRouteImport.update({
  id: '/profil-edit',
  path: '/profil-edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppPartenairesRoute = AppPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientRoute = AppClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AppRoute,
} as any)
const AppTachesAddRoute = AppTachesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppTachesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-api': typeof TestApiRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/client': typeof AppClientRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/partenaires': typeof AppPartenairesRoute
  '/app/profil': typeof AppProfilRoute
  '/app/profil-edit': typeof AppProfilEditRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/taches/add': typeof AppTachesAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-api': typeof TestApiRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/client': typeof AppClientRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/partenaires': typeof AppPartenairesRoute
  '/app/profil': typeof AppProfilRoute
  '/app/profil-edit': typeof AppProfilEditRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/taches/add': typeof AppTachesAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-api': typeof TestApiRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/client': typeof AppClientRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/partenaires': typeof AppPartenairesRoute
  '/app/profil': typeof AppProfilRoute
  '/app/profil-edit': typeof AppProfilEditRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/taches/add': typeof AppTachesAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/register'
    | '/reset-password'
    | '/test-api'
    | '/unauthorized'
    | '/app/client'
    | '/app/documents'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/partenaires'
    | '/app/profil'
    | '/app/profil-edit'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app/users'
    | '/app/'
    | '/app/taches/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/register'
    | '/reset-password'
    | '/test-api'
    | '/unauthorized'
    | '/app/client'
    | '/app/documents'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/partenaires'
    | '/app/profil'
    | '/app/profil-edit'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app/users'
    | '/app'
    | '/app/taches/add'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/register'
    | '/reset-password'
    | '/test-api'
    | '/unauthorized'
    | '/app/client'
    | '/app/documents'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/partenaires'
    | '/app/profil'
    | '/app/profil-edit'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app/users'
    | '/app/'
    | '/app/taches/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestApiRoute: typeof TestApiRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taches': {
      id: '/app/taches'
      path: '/taches'
      fullPath: '/app/taches'
      preLoaderRoute: typeof AppTachesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risques': {
      id: '/app/risques'
      path: '/risques'
      fullPath: '/app/risques'
      preLoaderRoute: typeof AppRisquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ressources': {
      id: '/app/ressources'
      path: '/ressources'
      fullPath: '/app/ressources'
      preLoaderRoute: typeof AppRessourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projets': {
      id: '/app/projets'
      path: '/projets'
      fullPath: '/app/projets'
      preLoaderRoute: typeof AppProjetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil-edit': {
      id: '/app/profil-edit'
      path: '/profil-edit'
      fullPath: '/app/profil-edit'
      preLoaderRoute: typeof AppProfilEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/partenaires': {
      id: '/app/partenaires'
      path: '/partenaires'
      fullPath: '/app/partenaires'
      preLoaderRoute: typeof AppPartenairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/client': {
      id: '/app/client'
      path: '/client'
      fullPath: '/app/client'
      preLoaderRoute: typeof AppClientRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taches/add': {
      id: '/app/taches/add'
      path: '/add'
      fullPath: '/app/taches/add'
      preLoaderRoute: typeof AppTachesAddRouteImport
      parentRoute: typeof AppTachesRoute
    }
  }
}

interface AppTachesRouteChildren {
  AppTachesAddRoute: typeof AppTachesAddRoute
}

const AppTachesRouteChildren: AppTachesRouteChildren = {
  AppTachesAddRoute: AppTachesAddRoute,
}

const AppTachesRouteWithChildren = AppTachesRoute._addFileChildren(
  AppTachesRouteChildren,
)

interface AppRouteChildren {
  AppClientRoute: typeof AppClientRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPartenairesRoute: typeof AppPartenairesRoute
  AppProfilRoute: typeof AppProfilRoute
  AppProfilEditRoute: typeof AppProfilEditRoute
  AppProjetsRoute: typeof AppProjetsRoute
  AppRessourcesRoute: typeof AppRessourcesRoute
  AppRisquesRoute: typeof AppRisquesRoute
  AppTachesRoute: typeof AppTachesRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientRoute: AppClientRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParametresRoute: AppParametresRoute,
  AppPartenairesRoute: AppPartenairesRoute,
  AppProfilRoute: AppProfilRoute,
  AppProfilEditRoute: AppProfilEditRoute,
  AppProjetsRoute: AppProjetsRoute,
  AppRessourcesRoute: AppRessourcesRoute,
  AppRisquesRoute: AppRisquesRoute,
  AppTachesRoute: AppTachesRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestApiRoute: TestApiRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
