# Generated by Django 6.0.5 on 2026-06-05 10:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profils/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dernier_connexion', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.permission')),
            ],
            options={
                'db_table': 'ramaqs_management_plateforme_utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChefProjet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ramaqs_management_plateforme.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ramaqs_management_plateforme.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ramaqs_management_plateforme.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ramaqs_management_plateforme.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ramaqs_management_plateforme.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('objectsif', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('avancement_globale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('domaine', models.CharField(max_length=100)),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_chef', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_client', to=settings.AUTH_USER_MODEL)),
                ('partenaires', models.ManyToManyField(related_name='projets_partenaire', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'projets',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priorite', models.CharField(max_length=50)),
                ('avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'taches',
            },
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_echeance', models.DateField()),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='ramaqs_management_plateforme.tache')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'sous_taches',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('projet', models.ManyToManyField(related_name='ressources', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'ressources',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('type_message', models.CharField(default='texte', max_length=50)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ramaqs_management_plateforme.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('valeur_cible', models.FloatField()),
                ('valeur_actuelle', models.FloatField()),
                ('unite', models.CharField(max_length=255)),
                ('seuil_alerte', models.FloatField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'kpis',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('chemin', models.FileField(upload_to='documents/')),
                ('version', models.CharField(max_length=20)),
                ('taille', models.IntegerField()),
                ('type_fichier', models.CharField(max_length=50)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ramaqs_management_plateforme.tache')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'commentaires',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_total', models.FloatField()),
                ('montant_depense', models.FloatField()),
                ('montant_restant', models.FloatField()),
                ('devise', models.CharField(default='EUR', max_length=10)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='ramaqs_management_plateforme.projet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tenant')),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur RAMAQS'), ('direction', 'Direction RAMAQS'), ('chef_projet', 'Chef de projet'), ('consultant', 'Consultant'), ('client', 'Client'), ('partenaire', 'Partenaire')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('invite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ramaqs_management_plateforme.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['tenant', 'statut'], name='taches_tenant__cef135_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['tenant', 'consultant'], name='taches_tenant__58a632_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['tenant', 'statut'], name='projets_tenant__59e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['tenant', 'date_debut'], name='projets_tenant__ed0e25_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'utilisateur', 'lue'], name='notificatio_tenant__e80ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant', 'conversation', 'date_envoi'], name='messages_tenant__a3a29c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
