# Generated by Django 6.0.5 on 2026-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('direction', 'Direction'), ('chef_projet', 'Chef de projet'), ('consultant', 'Consultant'), ('client', 'Client'), ('partenaire', 'Partenaire')], default='consultant', max_length=20),
        ),
    ]
