# Generated by Django 6.0.5 on 2026-06-07 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0003_utilisateur_entreprise_utilisateur_poste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='priorite',
            field=models.CharField(default='normale', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_debut_partenariat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_fin_partenariat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='partenaires',
            field=models.ManyToManyField(limit_choices_to={'role': 'partenaire'}, related_name='projets_partenaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
