# Generated by Django 6.0.5 on 2026-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0004_projet_priorite_utilisateur_date_debut_partenariat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_envoi']},
        ),
        migrations.AddField(
            model_name='notification',
            name='entite_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='entite_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'utilisateur', '-date_envoi'], name='notificatio_tenant__38a125_idx'),
        ),
    ]
