# Generated by Django 6.0.5 on 2026-06-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0005_alter_notification_options_notification_entite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ramaqs_management_plateforme.projet'),
        ),
    ]
