# Generated by Django 6.0.5 on 2026-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0006_notification_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('attention', 'Attention'), ('erreur', 'Erreur')], default='info', max_length=100),
        ),
    ]
