# Generated by Django 6.0.5 on 2026-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
