# Generated by Django 6.0.5 on 2026-06-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0009_alter_document_options_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_fichier',
            field=models.CharField(choices=[('document', 'Document'), ('livrable', 'Livrable'), ('rapport', 'Rapport'), ('contrat', 'Contrat')], default='document', max_length=50),
        ),
    ]
