# Generated by Django 6.0.5 on 2026-06-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0010_alter_document_type_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='justification_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut_approbation',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20, null=True),
        ),
    ]
