# Generated by Django 6.0.5 on 2026-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0011_utilisateur_approuve_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False),
        ),
    ]
