# Generated by Django 6.0.5 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0012_utilisateur_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('en_attente_validation', 'En attente de validation'), ('termine', 'Terminé')], default='a_faire', max_length=50),
        ),
    ]
