# Generated by Django 6.0.5 on 2026-06-17 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0014_remove_projet_chef_projet_projet_chefs_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='chefs_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='chef_projet',
            field=models.ManyToManyField(related_name='projets_chef', to=settings.AUTH_USER_MODEL),
        ),
    ]
