# Generated by Django 6.0.5 on 2026-06-17 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0015_remove_projet_chefs_projet_projet_chef_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='chemin',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type_fichier',
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_par',
        ),
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(default='', upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('livrable', 'Livrable'), ('document', 'Document'), ('rapport', 'Rapport'), ('contrat', 'Contrat')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='taille',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
          sql="""
              UPDATE "documents"
              SET "version" = CASE
                  WHEN "version" ~ '^[0-9]+(\\.[0-9]+)?$' THEN ROUND("version"::numeric)::text
                  ELSE '1'
              END
              WHERE "version" IS NOT NULL;
          """,
          reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
