# Generated by Django 6.0.5 on 2026-06-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0016_remove_document_chemin_remove_document_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefprojet',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'default_manager_name': 'objects'},
        ),
    ]
