# Generated by Django 6.0.5 on 2026-06-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramaqs_management_plateforme', '0017_alter_chefprojet_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='avancement_globale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
